<template>
  <section
    :class="[
      'relative',
      'py-16',
      'flex',
      'flex-col',
      'justify-center',
      'items-start',
      'px-2',
      'sm:px-10',
      'w-full', 
      'glass',
      'bg-primary/20',
      'text-neutral',
      'backdrop-blur-lg',
      'shadow-lg',
      'rounded-b-lg',
      $attrs.class
    ]"
  >
    <slot />
  </section>
</template>