version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  andrepg_website:
    image: "node:lts-alpine"
    container_name: andrepg_website
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ..:/workspaces/andrepg.github.io:cached
    ports:
      - "5173:5173"
    networks:
      - andrepg
    command: /bin/sh -c "while sleep 1000; do :; done"

networks:
  andrepg:
    driver: bridge
 
